<?php

declare(strict_types = 1);

namespace Sweetchuck\ComposerSuite\Test\Unit\Composer\Command;

use Composer\Console\Application;
use Sweetchuck\ComposerSuite\Composer\Command\GenerateCommand;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Tester\CommandTester;

/**
 * @covers \Sweetchuck\ComposerSuite\Composer\Command\GenerateCommand<extended>
 */
class GenerateTest extends CommandTestBase
{

    public function testSuiteGenerateSuccess()
    {
        $projectRoot = $this->createTmpDir();
        $this->fs->dumpFile(
            "$projectRoot/composer.json",
            json_encode([
                'config' => [
                    'allow-plugins' => [
                        'sweetchuck/composer-suite' => true,
                        'sweetchuck/git-hooks' => true,
                    ],
                ],
                'require' => [
                    'a/b' => '^1.0',
                ],
                'extra' => [
                    'composer-suite' => [
                        'one' => [
                            'actions' => [
                                [
                                    'type' => 'replaceRecursive',
                                    'config' => [
                                        'parents' => [],
                                        'items' => [
                                            'require' => [
                                                'a/b' => '1.x-dev',
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                        'two' => [
                            'actions' => [
                                [
                                    'type' => 'replaceRecursive',
                                    'config' => [
                                        'parents' => [],
                                        'items' => [
                                            'require' => [
                                                'a/b' => '1.x-dev',
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                        'three' => [
                            'actions' => [
                                [
                                    'type' => 'replaceRecursive',
                                    'config' => [
                                        'parents' => [],
                                        'items' => [
                                            'require' => [
                                                'a/b' => '1.x-dev',
                                            ],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ])
        );

        putenv('COMPOSER=' . "$projectRoot/composer.json");

        $application = new Application();
        $command = new GenerateCommand('suite:generate');
        $command->setApplication($application);
        $commandTester = new CommandTester($command);
        $commandTester->execute(
            [],
            [
                'decorated' => false,
                'verbosity' => OutputInterface::VERBOSITY_VERY_VERBOSE,
            ],
        );

        /** @var \Symfony\Component\Console\Output\StreamOutput $stdOutput */
        $stdOutput = $commandTester->getOutput();
        $handler = $stdOutput->getStream();
        fseek($handler, 0);
        $this->tester->assertSame('', stream_get_contents($handler));

        $expectedExitCode = 0;
        $this->tester->assertSame(
            $expectedExitCode,
            $commandTester->getStatusCode(),
            "exit code $expectedExitCode",
        );

        $comment = '"DO NOT EDIT THIS FILE. Content of this file can be overwritten by the `suite:generate` command."';

        $this->tester->assertFileExists("$projectRoot/composer.one.json");
        $this->tester->assertStringEqualsFile(
            "$projectRoot/composer.one.json",
            implode("\n", [
                '{',
                '    "_comment": [',
                "        $comment",
                '    ],',
                '    "config": {',
                '        "allow-plugins": {',
                '            "sweetchuck/composer-suite": true,',
                '            "sweetchuck/git-hooks": true',
                '        }',
                '    },',
                '    "require": {',
                '        "a/b": "1.x-dev"',
                '    },',
                '    "extra": []',
                '}',
                '',
            ]),
        );
        $this->tester->assertFileExists("$projectRoot/composer.two.json");
        $this->tester->assertFileExists("$projectRoot/composer.three.json");
    }

    public function testSuiteGenerateFail()
    {
        // In the background Composer uses \realpath(), which doesn't work
        // together with vfs://.
        $projectRoot = $this->createTmpDir();
        $this->fs->dumpFile(
            "$projectRoot/composer.json",
            json_encode([
                'require' => [
                    'a/b' => '^1.0',
                ],
                'extra' => [
                    'composer-suite' => [
                        'one' => [
                            'actions' => [
                                [
                                    'type' => 'sortNormal',
                                    'config' => [
                                        'parents' => [],
                                        'function' => 'not_valid',
                                    ],
                                ],
                            ],
                        ],
                    ],
                ],
            ])
        );

        putenv('COMPOSER=' . "$projectRoot/composer.json");

        $application = new Application();
        $command = new GenerateCommand('suite:generate');
        $command->setApplication($application);
        $commandTester = new CommandTester($command);
        $commandTester->execute(
            [],
            [
                'verbosity' => OutputInterface::VERBOSITY_VERY_VERBOSE,
            ],
        );

        $expectedExitCode = 1;
        $this->tester->assertSame(
            $expectedExitCode,
            $commandTester->getStatusCode(),
            "exit code $expectedExitCode",
        );

        $this->tester->assertFileDoesNotExist("$projectRoot/composer.one.json");
    }
}
